# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b253f081e314f7e641eff11682cb1f04ef591ea96e8d668670c68d75e8c9a438ed63e886f57fa09044117d9840aebf2c1b38bc90f2d198ba7d3605040d20f41c

test:
  secret_key_base: 1d9ce4893e643092fd7761110f1f20d1f21bcd8e43694761d2d96e8de7fa9c13861459a9b568ba206a536223118f1149b8ada6c2177cf9b0b89051537116236c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
